[project]
name = "pyisam"
version = "0.20.0"
description = "Python3 interface to ISAM data"
authors = [
    {name = "Richard Moseley", email = "richard.moseley4@gmail.com"},
]
dependencies = [
    "cffi-buildtool",
    "meson-python",
    "ninja",
]
requires-python = ">=3.13"
readme = "README.md"
license = {text = "MIT"}

[build-system]
build-backend = "mesonpy"
requires = ["meson-python", "cffi-buildtool"]

[tool.meson-python.args]
setup = [
  "-Dpython.install_env=venv",
  "-Dffisupp=cffi,ctypes",
]
