#define isrollback VBisrollback
#define islogopen VBislogopen
#define isaddindex VBisaddindex
#define isaudit VBisaudit
#define isdelcurr VBisdelcurr
#define iserase VBiserase
#define isrecover VBisrecover
#define isbegin VBisbegin
#define isunlock VBisunlock
#define islogclose VBislogclose
#define isrewcurr VBisrewcurr
#define isstart VBisstart
#define isdelrec VBisdelrec
#define isdelete VBisdelete
#define isrewrec VBisrewrec
#define isdelindex VBisdelindex
#define isrewrite VBisrewrite
#define iscleanup VBiscleanup
#define iscommit VBiscommit
#define isuniqueid VBisuniqueid
#define isindexinfo VBisindexinfo
#define iswrcurr VBiswrcurr
#define isopen VBisopen
#define iscluster VBiscluster
#define isflush VBisflush
#define isbuild VBisbuild
#define isrelease VBisrelease
#define iswrite VBiswrite
#define islock VBislock
#define isread VBisread
#define isrename VBisrename
#define isclose VBisclose
#define issetunique VBissetunique
#define ldint VBldint
#define ldlong VBldlong
#define lddblnull VBlddblnull
#define ldfltnull VBldfltnull
#define ldfloat VBldfloat
#define ldchar VBldchar
#define lddecimal VBlddecimal
#define lddbl VBlddbl
#define stchar VBstchar
#define stfloat VBstfloat
#define stdecimal VBstdecimal
#define stfltnull VBstfltnull
#define stdblnull VBstdblnull
#define stint VBstint
#define stlong VBstlong
#define stdbl VBstdbl
#define deccvdbl VBdeccvdbl
#define deccopy VBdeccopy
#define deccvint VBdeccvint
#define dectoflt VBdectoflt
#define decdiv VBdecdiv
#define deccvlong VBdeccvlong
#define dectolong VBdectolong
#define dectoasc VBdectoasc
#define dececvt VBdececvt
#define dectodbl VBdectodbl
#define decsub VBdecsub
#define decadd VBdecadd
#define decmul VBdecmul
#define deccvasc VBdeccvasc
#define decfcvt VBdecfcvt
#define deccmp VBdeccmp
#define deccvflt VBdeccvflt
#define dectoint VBdectoint
